create table public.card_suits (
  id bigint generated by default as identity not null,
  name text not null default '',
  created_at timestamp with time zone not null default (now() at time zone 'utc'),
  value text null default '',
  position smallint not null default 0,
  constraint card_suits_pkey primary key (id)
);

ALTER TABLE "public"."card_suits" ENABLE ROW LEVEL SECURITY;
