create table public.card_numbers (
  id bigint generated by default as identity not null,
  value smallint null,
  created_at timestamp with time zone not null default (now() at time zone 'utc'),
  name text not null default '',
  constraint card_numbers_pkey primary key (id)
);

ALTER TABLE "public"."card_numbers" ENABLE ROW LEVEL SECURITY;
