create table public.card_codes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() at time zone 'utc'),
  suit_id bigint not null,
  number_id bigint not null,
  constraint card_indexes_pkey primary key (id),
  constraint unique_card_code unique (suit_id, number_id),
  constraint card_indexes_number_id_fkey foreign KEY (number_id) references card_numbers (id),
  constraint card_indexes_suit_id_fkey foreign KEY (suit_id) references card_suits (id)
);

ALTER TABLE "public"."card_codes" ENABLE ROW LEVEL SECURITY;
