create table public.card_concept_series_presets (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'utc'),
    title text not null default '',
    description text not null default '',
    author_id uuid null default auth.uid (),
    constraint card_concept_series_presets_pkey primary key (id),
    constraint card_concept_series_presets_author_id_fkey foreign KEY (author_id) references auth.users (id)
);

ALTER TABLE "public"."card_concept_series_presets" ENABLE ROW LEVEL SECURITY;
