create table public.card_concept_series_preset_codes (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'utc'),
    preset_id bigint not null,
    code_id bigint not null,
    constraint card_concept_series_preset_codes_pkey primary key (id),
    constraint card_concept_series_preset_codes_code_id_fkey foreign KEY (code_id) references card_codes (id),
    constraint card_concept_series_preset_codes_preset_id_fkey foreign KEY (preset_id) references card_concept_series_presets (id)
);

ALTER TABLE "public"."card_concept_series_preset_codes" ENABLE ROW LEVEL SECURITY;
