create table public.card_concepts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'),
    code_id bigint not null,
    concept text null default '',
    series_id bigint not null,
    author_id uuid not null,
    updated_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'),
    sort_order smallint not null default 0,
    constraint card_concepts_pkey primary key (id),
    constraint card_concepts_unique unique (code_id, series_id),
    constraint card_concepts_author_id_fkey foreign KEY (author_id) references auth.users (id),
    constraint card_concepts_code_id_fkey foreign KEY (code_id) references card_codes (id),
    constraint card_concepts_series_id_fkey foreign KEY (series_id) references card_concept_series (id)
);

ALTER TABLE "public"."card_concepts" ENABLE ROW LEVEL SECURITY;
